name: Build Agents

on:
  push:
    branches:
      - "release-*"
      - "windows_agent"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: 🎉 Build
        run: |
          mkdir /tmp//to_upload
          sudo apt install makeself -y

          # UBUNTU
          cd ./ubuntu/
          ./build.sh
          cd ../

          # DEBIAN
          cd ./debian/
          ./build.sh
          cd ../

          # WINDOWS
          cd ./windows/
          ./build.sh
          cd ../

          ls -la /tmp/to_upload/

      # - name: 📂 Sync files
      #   uses: SamKirkland/FTP-Deploy-Action@4.1.0
      #   with:
      #     server: ${{ secrets.FTP_HOST }}
      #     username: ${{ secrets.FTP_USER }}
      #     password: ${{ secrets.FTP_PWD }}
      #     server-dir: www/wp-content/uploads/agents/
      #     local-dir: /tmp/to_upload/
